name: Release

on: 
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

env:
  BUILD_SH: fetch.sh

jobs:
  Build:
    name: "Release"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@master
      - name: 'Build'
        run: |
          chmod +x $BUILD_SH
          ./$BUILD_SH ${{ secrets.TOKEN }}
      
      - name: 'Release'
        uses: softprops/action-gh-release@master
        with:
          prerelease: false
          generate_release_notes: false
          tag_name: 'latest'
          files: |
            AIO.zip
            AIO-pre.zip
            Arcane.zip
            Arcane-pre.zip
            EdiZon-Overlay.zip
            FanControl.zip
            FPSLocker.zip
            JKSV.zip
            ldn_mitm.zip
            hbmenu.nsp
            nso-icon-tool.zip
            oc-tester.zip
            oc-testing-save.zip             
            pkgs-Magic-pre.zip
            pkgs-Magic.zip
            pkgs-Settings-pre.zip
            pkgs-Settings.zip
            pkgs-Guides.zip
            pkgs-R2Config.zip
            pkgs-Updater-pre.zip
            pkgs-Updater.zip
            ReverseNX-RT.zip
            SaltyNX.zip
            Status-Monitor-Overlay-pre.zip
            Status-Monitor-Overlay.zip
            sys-clk-oc-pre.zip
            sys-clk-oc.zip
            update.bin
            wiliwili.zip
            NX-60FPS-RES-GFX-Cheats.zip
            60FPSLocker.zip
            NX-Activity-Log.zip