name: Release

on: 
  push:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
env:
  BUILD_SH: fetch.sh

jobs:
  Build:
    name: "Release"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: 'Build'
        run: |
          chmod +x $BUILD_SH
          ./$BUILD_SH ${{ secrets.TOKEN }}

      - name: 'Release'
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: false
          tag_name: 'latest'
          files: |
            FanControl.zip
            ldn_mitm.zip
            hbmenu.nsp
            nso-icon-tool.zip
            oc-tester.zip
            oc-testing-save.zip             
            SaltyNX.zip
            sys-clk-oc-pre.zip
            sys-clk-oc.zip
            sys-patch.zip
            update.bin
            wiliwili.zip
            NX-60FPS-RES-GFX-Cheats.zip
            60FPSLocker.zip
            NX-Activity-Log.zip
            SimpleModDownloader.zip
            SimpleModManager.zip
            nyx.zip
            chiaki-ng.zip
            theme.zip
            nx-locale-switcher.zip